### PR TITLE
#40 - Tagged volume create/remove tasks.

### LINKED ISSUE #40: deploy_service_deploy should enable managing volumes without touching services/configs

### PR DESCRIPTION
**Pull request by micahkemp-splunk**
Closes #40

### CODE REVIEW

**Comment by micahkemp-splunk** [comment]
I'll test this against a dev infrastructure before merging, but wanted to give an early view into how I was thinking this would work.

**Comment by micahkemp-splunk** [comment]
I wanted to add a "configure volumes for all services" bit to the provision docker nodes playbook, but a playbook can't limit which tags are run in specific tasks, so it wouldn't do any good.

**Comment by micahkemp-splunk** [comment]
Tested on dev swarm and seems to work as expected.

**Review by mason-splunk — APPROVED** [review]

**Comment by mason-splunk** [comment]
@micahkemp-splunk I'll leave it up to you to determine when a new release tag would be appropriate to add.

**Pull request merged**
